### ISSUE TITLE
Warning: R expressions in yaml.load will not be auto-evaluated by default in the near future

### ISSUE THREAD

**Issue by kevinykuo** [jjallaire/config#12]
Sample results from tests:
```
Warnings -----------------------------------------------------------------------
1. configurations inherit from default (@test-inherit.R#4) - R expressions in yaml.load will not be auto-evaluated by default in the near future

2. configurations can inherit from other configurations (@test-inherit.R#10) - R expressions in yaml.load will not be auto-evaluated by default in the near future
```

Related commit in `yaml`: https://github.com/viking/r-yaml/commit/a3c96ba262c1fe77b564cf6a4ed9c4054ae2bc8c

Some of these are showing up intermittently in sparklyr.

**Comment by jjallaire** [comment]
Is there something we can do to turn on auto-evaluation in our call that parses the YAML? Could you send a PR for this if it's straightforward?

**Comment by bcollier** [comment]
second this problem consistently getting 

R expressions in yaml.load will not be auto-evaluated by default in the near future

**Comment by jjallaire** [comment]
@kevinykuo Could you provide a PR to the config package that resolves this?

**Comment by kevinykuo** [comment]
I think this is something that needs to be fixed upstream in yaml. Will follow up.
