### ISSUE TITLE
get cannot find config.yml in parent directories under Linux

### ISSUE THREAD

**Issue by spkaluzny** [jjallaire/config#15]
config::get cannot find config.yml in parent directories under Linux. 

On Linux, normalizePath is the same as the file
    `normalizePath("config.yml", must=FALSE)`
     `#> [1] "config.yml"`
On Windows, normalizePath is the full path to the file:
    `normalizePath("config.yml", must=FALSE)`
     `#> [1] "f:\\tmp\\config.yml"`

The while loop in config::get never moves up to the parent directory.

**Comment by jjallaire** [comment]
I'm not seeing this behavior (it does move up for me).

Could you provide a git repo that has a minimum reproducible example?

**Comment by dietrichson** [comment]
Having the same problem.

Here's a minimal example of behavior on my machine:

https://github.com/dietrichson/config-issue_15

specifically I used this file for testing:

https://github.com/dietrichson/config-issue_15/blob/issue_15/subfolder/config_test.R

**Comment by dietrichson** [comment]
**UPDATE:**
@spkaluzny , @jjallaire 
Rebuilding the package from the github source fixed the issue for me.

**Comment by spkaluzny** [comment]
I was using version 0.2 of config from CRAN when I reported this issue. Like @dietrichson, I do not see the problem when I use the github version of the package.

**Comment by landroni** [comment]
I too noticed this issue in 0.2, but can confirm that it's fixed in 0.3 (released on CRAN). This ticket can probably be closed.
