### ISSUE TITLE
Config file config.yml not found in current working directory or parent directories

### ISSUE THREAD

**Issue by aborderon** [jjallaire/config#22]
Hello,

I have a problem with OpenCPU, it does not find the config.yml.

I have no problem to use it in development, I access the different variables of my config.yml file.

However once the package compiled and deployed on OpenCPU I get the following error message:

```
Config file config.yml not found in current working directory or parent directories
In call:
Config :: get ()
```

Yet my config.yml file is at the root of my package next to the folder R.

Do you have an idea of ​​my mistake?

I thank you in advance.

**Comment by johanneswaage** [comment]
If deploying as a package, your package functions won’t have access to files in the package root. You could place the file in inst/extdata as specified here: http://r-pkgs.had.co.nz/inst.html

**Comment by aborderon** [comment]
Hello, thank you for your return. Actually I moved the configuration file to the inst folder so I could use it during a deployment.
