### ISSUE TITLE
Bug for RefClass copy (base::get vs config::get)

### ISSUE THREAD

**Issue by nico-schmid** [jjallaire/config#26]
I might have found a bug which appears when using the copy method of RefClasses:
`library(config)`
`A <- setRefClass("A", fields = list(a = "numeric"))`
`a <- A()`
`b <- a$copy()`
Fehler in get(field, envir = selfEnv) : 
  unbenutztes Argument (envir = selfEnv)
`detach(package:config)`
`A <- setRefClass("A", fields = list(a = "numeric"))`
`a <- A()`
`b <- a$copy()`
The reasn seems to be that inside the `copy `method `get ` is called and not `base::get`

**Comment by shrektan** [comment]
I think you should always use `config` package by calling `config::get()`.

Attaching the library explicitly is not good due to the fact that `config::get()` conflicts with the `base::get()` and will cause trouble in many cases...

**Comment by nico-schmid** [comment]
Makes sense! Thanks for the hint!
