### ISSUE TITLE
Wrong interaction with renv

### ISSUE THREAD

**Issue by asitemade4u** [jjallaire/config#39]
When loading `config` with the last version of renv, I get this message:
```Error: package or namespace load failed for ‘config’:  package ‘config’ was installed before R 4.0.0: please re-install it```
Contrary to the [solutions](https://stackoverflow.com/questions/63390194/package-xxx-was-installed-before-r-4-0-0-please-re-install-it) readily available on the web, this takes place in a **fresh docker image** where:
- `config` was installed from scratch in the `dockerfile` itself
- I did a `renv::snapshot()` straight away, which did not yield any error
- I checked the `renv.lock` file and `config` is indeed present as:

```json
"config": {
      "Package": "config",
      "Version": "0.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "31d77b09f63550cee9ecb5a08bf76e8f"
    },
```

It is only when I do a `renv::load()` that I get the error message.
It only happens with `config`.
I therefore conclude the culprit is `config`, not `renv`.

Please help.

**Comment by andrie** [comment]
Can you please provide a minimal reproducible example?  Perhaps in the form of a minimal dockerfile that shows this problem?

**Comment by asitemade4u** [comment]
Yes of course. Attached is the dockerfile I am using
[dockerfile.zip](https://github.com/rstudio/config/files/7546550/dockerfile.zip)
.

**Comment by asitemade4u** [comment]
As for the rest of the docker stack, I am trying to isolate it but it is not so simple as it relies on a full development environment.

**Comment by andrie** [comment]
Thanks, can you please modify that dockerfile to make it minimal?  You install some linux dependencies that I assume are not necessary for the reprex?  Also, you have some COPY statements that are redundant and will fail.

**Comment by asitemade4u** [comment]
Yes you are right. Here you go
[dockerfile.zip](https://github.com/rstudio/config/files/7546645/dockerfile.zip)
.

**Comment by andrie** [comment]
Attaching zip files in issues just makes life difficult for other people.  Please post the text next time.

This is what you sent me.

```dockerfile
FROM rocker/r-base:4.1.1
# CHAPTER: Initial
# NOTE: create an R user 
ENV USER stsinc
# CHAPTER: Linux installs
# NOTE: Install base libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    gpg \
    libcurl4-openssl-dev \
    software-properties-common \
    sudo \
    && rm -rf /var/lib/apt/lists/*
# NOTE: Update
RUN updatedb
# NOTE: Install renv
ENV RENV_VERSION 0.14.0
RUN R -e "install.packages('renv')"
RUN R -e "install.packages('config')"
# NOTE: Go to bash
RUN bash
```

**Comment by asitemade4u** [comment]
I am trying my best to. Please give me some time to come up with a better `dockerfile` + test process. Thanks.

**Comment by andrie** [comment]
I'm unable to replicate.

I created a new project under R-4.1.0, put the project under `renv` control, and then ran:

```r
renv::install("config")
```

Then I loaded the `config` package without a problem.

**Comment by andrie** [comment]
I also tried this in a `rocker/rstudio` container, again without any problems.

To initialize `renv`:

```r
renv::init()`
```

Then `renv` discovered the `config` dependency, installed this, restarted the session, and everything works as expected.

Still unable to replicate.

**Comment by asitemade4u** [comment]
There must have been a bad interaction with another plugin because I 
unexpectedly found a way out of the issue.
Please consider the issue closed.
Thanks for the help!
