### ISSUE TITLE
Add warning on library(config) and make it explicit on git / docs

### ISSUE THREAD

**Issue by CorneeldH** [jjallaire/config#44]
Hi there, thanks for the package (and all the other stuff you guys do)! For a project we implemented renv and library calls etc and loaded packages at startup.

Then we ran into a R Studio error, apparently based on config. I found this issue: https://github.com/rstudio/config/issues/4

Two points:
- Could a much more clear warning be added that library(config) shouldn't be executed? In docs (now the examples are with config:: but no clear warning) and also a warning when executing library(config)
- Secondly, other packages get updated and functions get superseded and depreciated over a period of years to ease transition but also keep up with best practices. Can this be done for config as well? The above issue was in 2017 already. So at some point it seems okay to ask users to use a newly-named function.

Thanks for considering!

**Comment by andrie** [comment]
To throw a warning if the user calls `library(config)` is an interesting idea.  I am investigating.

**Comment by andrie** [comment]
CRAN will most likely not accept a package that throws a warning on attaching the library. That said, throwing a message is possible and probably acceptable.

Will it be helpful in your use case to throw a message instead of a warning?

**Comment by CorneeldH** [comment]
Yeah, definitely. 

I had in my code the config:: but added later on a library line to keep it simply in renv. A message would help. 

Thanks for the quick response!
