### ISSUE TITLE
Unexpected behavior with lists

### ISSUE THREAD

**Issue by kieran-mace** [jjallaire/config#53]
It seems that lists are being merged with `default` when they are missing an element. I would have expected the `members` object to not borrow from `default` if it has been declared within a config.

``` r
yaml <- '
default:
  department_name: "Whole Company"
  members:
    - name: John
      age: 30
    - name: Jane
      age: 25
    - name: Sally
      age: 35

data_science:
  department_name: "Data Science"
  members:
    - name: John
      age: 30
    - name: Jane
      age: 25
'

config::with_config(yaml, config::get("members", config = "data_science"))
#> [[1]]
#> [[1]]$name
#> [1] "John"
#> 
#> [[1]]$age
#> [1] 30
#> 
#> 
#> [[2]]
#> [[2]]$name
#> [1] "Jane"
#> 
#> [[2]]$age
#> [1] 25
#> 
#> 
#> [[3]]
#> [[3]]$name
#> [1] "Sally"
#> 
#> [[3]]$age
#> [1] 35
```

Specifically, in this example, `Sally` should not show up in the `data_science` configuration.

<sup>Created on 2024-11-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by kieran-mace** [comment]
If there is another way of structuring this data to achieve the desired effect, I'd be open to that too - It does however seem this would be the desirred behavior.

**Comment by andrie** [comment]
We should document this better, but it is expected behaviour.

The new values get merged recursively into the default values.

I could probably invent workaround using two separate values for  `all_members` and `team_members` and then have logic in your app that merges / replaces these in the way you want.
