### ISSUE TITLE
inheritance from other config files

### ISSUE THREAD

**Issue by shearerpmm** [jjallaire/config#7]
The inheritance feature is very attractive - my team is wondering if it can be extended. We have many config YAML files that configure different experiments with a common data science pipeline. Certain parts of the config are shared among all experiments; it would be nice to store these in a common base YAML config and have other experiment files inherit from this.

**Comment by jjallaire** [comment]
That's a great idea! Note that you could write your own function for this today by:

1) Calling `config::get()` with an explicit `file` argument for the common and experiment-specific config files respectively (so you'd retrieve two configs).

2) Using the `config::merge()` function to merge the experiment specific config into the common config, e.g. `config <- config::merge(common, experiment)`

**Comment by shearerpmm** [comment]
That's a good point. And it's not clear to me if adding this feature helps your overall design. Feel free to close if you think it's out-of-scope.

**Comment by jjallaire** [comment]
Okay, I'll close for now and potentially revisit in a future release if this proves a popular usage pattern. Thanks!
